services:
 mysql:
  image: mysql:8.0
  container_name: mysql_container
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: financesapidb
   MYSQL_USER: user
   MYSQL_PASSWORD: password
  ports:
   - "3308:3306"
  volumes:
   - mysql_data:/var/lib/mysql
  networks:
   - mynetwork
   
volumes:
 mysql_data:

networks:
 mynetwork: